### ISSUE TITLE
Alternate Star Orgs Logos

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/star-orgs#10]
![star_orgs](https://cloud.githubusercontent.com/assets/228256/16464886/3bd4aef2-3e0a-11e6-87da-4c10627471ae.png)
![star_orgs_2](https://cloud.githubusercontent.com/assets/228256/16464890/3da8cc4a-3e0a-11e6-8627-fed5823b3dff.png)
![star_orgs_color](https://cloud.githubusercontent.com/assets/228256/16464893/4038def0-3e0a-11e6-8a73-edc1a8451278.png)
![star_orgs_moar_color](https://cloud.githubusercontent.com/assets/228256/16464897/4215294a-3e0a-11e6-998b-05d130fe654f.png)

**Comment by kendaleiv** [comment]
Noting that these logos are adapted from "[Death Star](https://thenounproject.com/term/death-star/191002/)" by [Sergey Demushkin](https://thenounproject.com/mockturtle/) licensed under [CC BY 3.0 US](https://creativecommons.org/licenses/by/3.0/us/).
